// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectGoFile() {
  return window['go']['main']['App']['SelectGoFile']();
}
