// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeProject(arg1:string):Promise<Array<main.Finding>>;

export function SelectFolder():Promise<string>;

export function SelectGoFile():Promise<string>;
